Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,45 +1,62 @@
-# This file is a template, and might need editing before it works on your project.
-# You can copy and paste this template into a new `.gitlab-ci.yml` file.
-# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
-#
-# To contribute improvements to CI/CD templates, please follow the Development guide at:
-# https://docs.gitlab.com/ee/development/cicd/templates.html
-# This specific template is located at:
-# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml
+variables:
+  WORK_DIR: "/home/caratred/frappe-15/apps/ezy_hr"
+  #CURRENT_BRANCH: "$(git rev-parse --abbrev-ref HEAD)"
+  COMMIT_ID: $(git rev-parse --short "$CURRENT_BRANCH")
+  #ADMIN_EZYINVOICING_REPO_URL: https://jenkins:glpat-cLy2cXH2iVsP2mxoK_kj@gitlab.caratred.com/devops/admin_ezyinvoicing.git
+  #BRANCH_NAME: "uat_ezy_hr"
 
-# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options
+# Trigger the pipeline on a new commit to a uat_ezy_hr branch.
+workflow:
+  rules:
+    - if: $CI_COMMIT_BRANCH == "uat_ezy_hr" #$CI_DEFAULT_BRANCH
 
-# you can delete this line if you're not using Docker
-image: busybox:latest
+# Stages to define a workflow step by step.
+stages:
+  - check_repo
+  - update_repo
 
-before_script:
-  - echo "Before script section"
-  - echo "For example you might run an update here or install a build dependency"
-  - echo "Or perhaps you might print out some debugging details"
+check_repo_job:
+  stage: check_repo
+    # Verifying for Work directory if directory not exists then exit the pipeline.
+  script: |
+    
+      if [ -d "$WORK_DIR" ]; then
+            echo "$WORK_DIR repo exists."
+            git config --global --add safe.directory $WORK_DIR
+      else
+            echo "The $WORK_DIR repo not exists."
+            exit 1
+      fi
 
-after_script:
-  - echo "After script section"
-  - echo "For example you might do some cleanup here"
+update_repo-job:
+  stage: update_repo
+  # Change to the work directory and get the current branch, if curren branch is not uat_ezy_hr then exit the pipeline
+  # And check for any local changes in git repo, then pull the latest changes.
+  script: |
+        echo "Change to work directory"
+        cd "$WORK_DIR" || { echo "Failed to change directory"; exit 1; }
 
-build1:
-  stage: build
-  script:
-    - echo "Do your build here"
+          if [ -d .git ]; then
+              CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+                echo "The repository is currently on branch: $CURRENT_BRANCH"
+            if [ "$CURRENT_BRANCH" == "uat_ezy_hr" ]; then
+                  echo "Checking for any local changes in the repo and backup last git commit ID"
+                  git log -1 >>/home/caratred/deepak/git-commit.log
+              if [[ -n $(git status -s) ]]; then
+                    echo "Error: There are local changes. Please commit or stash them before pulling."
+                      exit 1
+                else  
+                    echo "No local changes found, pulling code from $CURRENT_BRANCH"
+                    git pull origin "$CURRENT_BRANCH"
+              fi
+                else
+                  echo "$WORK_DIR repo is not on the uat_ezy_hr branch. Current branch: $CURRENT_BRANCH"
+                  exit 1
+            fi
+                else
+                  echo "$WORK_DIR directory is not a Git repository"
+                  exit 1
+          fi
 
-test1:
-  stage: test
-  script:
-    - echo "Do a test here"
-    - echo "For example run a test suite"
 
-test2:
-  stage: test
-  script:
-    - echo "Do another parallel test here"
-    - echo "For example run a lint test"
 
-deploy1:
-  stage: deploy
-  script:
-    - echo "Do your deploy here"
-  environment: production
